gateway:
  port: 8080
  readTimeout: 5s
  writeTimeout: 5s
  middlewares:
    - logger      # Global middleware applied to all endpoints

endpoints:
  - name: HTTPBin
    path: /httpbin
    target: https://httpbin.org/get
    method: GET
    headers:
      X-My-Header:
        - MyValue
        - AnotherValue
    allowed_headers:
      - X-Another-Header
    middlewares:
      - cors      # Per-endpoint middleware
      - auth      # Another per-endpoint middleware

  - name: PostEndpoint
    path: /post
    target: https://httpbin.org/post
    method: POST
