gateway:
  port: 8080
  readTimeout: 5s
  writeTimeout: 5s
  middlewares:
    - logger
    - cors

endpoints:
  - name: HTTPBin
    path: /httpbin
    target: https://postman-echo.com/get
    method: GET
    headers:
      X-My-Header:
        - MyValue
        - AnotherValue
    allowed_headers:
      - X-Another-Header
      - X-Request-Id

  - name: PostEndpoint
    path: /post
    target: https://httpbin.org/post
    method: POST

  - name: Authenticated HTTPBin
    path: /auth/httpbin
    target: https://httpbin.org/get
    method: GET
    middlewares:
      - basicAuth
