version: '3'

tasks:
  lint:
    desc: Run lint
    deps:
      - lint:install
    cmds:
      - golangci-lint run --timeout 5m

  lint:install:
    desc: Install golangci-lint
    status:
      - test -f ${GOBIN}/golangci-lint
    cmds:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.0.2

  test:
    desc: Run tests
    deps:
      - test:install
    cmds:
      - gotestsum ./... -- -race -count=1 -v

  test:install:
    desc: Install gotestsum
    status:
        - test -f ${GOBIN}/gotestsum
    cmds:
        - go install gotest.tools/gotestsum@latest
