version: '3'

tasks:
  lint:
    desc: Run lint
    deps:
      - lint:install
    cmds:
      - golangci-lint run --timeout 5m

  lint:install:
    desc: Install golangci-lint
    status:
      - test -f ${GOBIN}/golangci-lint
    cmds:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.0.2
